# -*- coding: utf-8 -*-
"""netflix_data_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151bJ8S43hD0B6aiw3aHGFz4uGZm7_qaQ
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv("netflixdata.csv")

df.head()

df.shape

df.columns

df = df.iloc[:, :12]

df.head()

df.isnull().sum()

df.drop_duplicates(inplace=True)

sns.countplot(
    x="type",
    data=df
)

plt.title("Movies vs TV Shows")

plt.show()

genre=df["listed_in"].value_counts().head(10)

genre.plot(
    kind="bar",
    figsize=(10,5)
)

plt.title("Top Netflix Genres")

plt.show()

plt.figure(figsize=(12,5))

df["release_year"].value_counts().sort_index().plot()

plt.title("Netflix Content Growth")

plt.show()

movies=df[
["title","description","listed_in"]
]

movies["content"] = (
movies["description"]+" "+
movies["listed_in"]
)

vectorizer=TfidfVectorizer(
stop_words="english"
)


matrix=vectorizer.fit_transform(
movies["content"]
)

similarity=cosine_similarity(matrix)

def recommend(movie):

    index = movies[
    movies["title"]==movie
    ].index[0]


    scores=list(
    enumerate(similarity[index])
    )


    scores=sorted(
    scores,
    key=lambda x:x[1],
    reverse=True
    )


    for i in scores[1:6]:
        print(
        movies.iloc[i[0]]["title"]
        )


recommend("The Matrix")

similarity[0][1]

data = df.copy()

# fill missing values
data.fillna("Unknown", inplace=True)


# convert type
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["type"] = le.fit_transform(data["type"])


# create useful features

data["duration_num"] = (
    data["duration"]
    .str.extract('(\d+)')
    .astype(float)
)


data["genre_count"] = (
    data["listed_in"]
    .apply(lambda x: len(str(x).split(",")))
)


data.head()

X = data[
[
"release_year",
"duration_num",
"genre_count"
]
]

y = data["type"]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    random_state=42
)


model.fit(
    X_train,
    y_train
)


prediction=model.predict(X_test)


accuracy=accuracy_score(
    y_test,
    prediction
)


print("Accuracy:",accuracy*100,"%")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt


cm = confusion_matrix(
    y_test,
    prediction
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()